services:
  main:
    env_file: ".env"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - DEV_BUILD=true
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}:/app
    ports:
      - 5000:5000
