services:
  main:
    env_file: ".env"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - DEV_BUILD=true
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ${PWD}:/app
