name: CI

on: [ push, pull_request, commit ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pip install poetry==1.7.1
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install -vv
    - name: Test
      run: poetry run pytest
